version: '3.1'

services:

  reiport_db:
    container_name: reiport_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./dataBase.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - app-network

  reiport-redis:
    container_name: reiport-redis
    image: redis/redis-stack:latest
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - app-network

  reiport_db_interface:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
